version: "3.3"
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - wordpressMariaDB:/var/lib/mysql
    ports:
      - '3306:3306'
  server:
    image: 'wordpress'
    environment:
      WORDPRESS_DB_HOST: 'mariadb'
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'admin'
      WORDPRESS_DB_NAME: 'wordpress'
    volumes:
      - ./src:/var/www/html
    ports:
      - '8080:80'
volumes:
  wordpressMariaDB:
    external: true
  wordpress: