version: "3.3"
services:
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - wordpressMysql:/var/lib/mysql
    ports:
      - '3306:3306'
  server:
    image: 'wordpress'
    environment:
      WORDPRESS_DB_HOST: 'mysql'
      WORDPRESS_DB_USER: 'admin'
      WORDPRESS_DB_PASSWORD: 'admin'
      WORDPRESS_DB_NAME: 'wordpress'
    volumes:
      - ./src:/var/www/html
    ports:
      - '8080:80'
volumes:
  wordpressMysql:
    external: true
  wordpress: